<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-3KHPK879" ignored="0" name="TestNGExample" tests="3" failures="1" timestamp="2023-03-30T14:20:18 EDT" time="0.06" errors="0">
  <testcase name="userCanAddProduct" time="0.0" classname="com.automation.test.AddCart">
    <failure type="java.lang.RuntimeException" message="Test Failed">
      <![CDATA[java.lang.RuntimeException: Test Failed
at com.automation.test.AddCart.userCanAddProduct(AddCart.java:9)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- userCanAddProduct -->
  <testcase name="userCanDeleteProduct" time="0.0" classname="com.automation.test.AddCart">
    <skipped/>
  </testcase> <!-- userCanDeleteProduct -->
  <testcase name="userCanPurchaseProduct" time="0.0" classname="com.automation.test.AddCart">
    <skipped/>
  </testcase> <!-- userCanPurchaseProduct -->
</testsuite> <!-- TestNGExample -->
